In [1]:
import numpy as np


# creating numpy arrays


In [2]:
x=[1,2,3]
np.array(x,np.int32)

array([1, 2, 3])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((2,3),int)

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
y=np.identity(5)

In [8]:
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy arrays properties and attributes


In [11]:
y.shape

(5, 5)

In [12]:
y.size

25

In [13]:
y.itemsize

8

In [14]:
y.dtype

dtype('float64')

In [15]:
y.ndim

2

In [20]:
a=y.astype("int")

In [21]:
a.dtype

dtype('int32')

In [22]:
a.itemsize


4

In [23]:
b=np.arange(10)


In [24]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
c=b.reshape(2,5)

In [36]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])